### ISSUE TITLE
can not "predict" in other python file by loading saved model

### ISSUE THREAD

**Issue by pxlong** [tflearn/tflearn#31]
Hi, 

I have trained a model using the attached train.py (github does not allow to load .py, so I changed it to .txt). After that, I am going to test the saved model on some new data (by using predict.py). But I got some problems here, you can see the errors in the error_output.txt. 
Did I miss sth about checkpoint file? I really don't know how to fix it.
Thanks.

[error_ouput.txt](https://github.com/tflearn/tflearn/files/217922/error_ouput.txt)
[predict.py.txt](https://github.com/tflearn/tflearn/files/217913/predict.py.txt)
[train.py.txt](https://github.com/tflearn/tflearn/files/217914/train.py.txt)

**Comment by aymericdamien** [comment]
Hi, I took a look at your code, I tried it on MNIST data, and it was working fine for me:
Predict 1 example:
```
Aymerics-MacBook-Pro:~ aymeric$ ~/anaconda2/bin/ipython test4.py 
Extracting mnist/train-images-idx3-ubyte.gz
Extracting mnist/train-labels-idx1-ubyte.gz
Extracting mnist/t10k-images-idx3-ubyte.gz
Extracting mnist/t10k-labels-idx1-ubyte.gz
[7]
```

From the error file you sent, it seems that your model file has problem (maybe corrupted?) because the model cannot find the weights in it.

What version of TensorFlow are you using? is it 0.7+? Also, if you doesn't have the latest version of TFLearn, please update it and see if it fix this issue:

```
pip uninstall tflearn
pip install git+https://github.com/tflearn/tflearn.git
```

**Comment by aymericdamien** [comment]
Here is a notebook: 
[issue31.ipynb.txt](https://github.com/tflearn/tflearn/files/218350/issue31.ipynb.txt)

**Comment by pxlong** [comment]
@aymericdamien Thanks for your reply. 
I just installed tensorflow and tflearn two days ago, so I think they are both latest versions. 
Yes, I run the train.py multiple times, so I need to delete some files to fix it?

**Comment by aymericdamien** [comment]
If you are using command line, you can run as many time as you want, because every time you re-run a python file, it reset the default graph.
My point was that maybe, if you are using notebooks for example, you run a part of the graph multiple time, so at every run, you add some new ops to the default graph (because the default graph is not reset).

For example, if you want to define 2 same model in a same python file, you need to specify a graph to store them (instead of using the default graph):
```
graph1 = tf.Graph()
with graph1.as_default():
    your_model_for_training
    model.save(...)

graph2 = tf.Graph()
with graph2.as_default():
    your_model_for_testing
    model.load(...)
    model.predict(...)
```

**Comment by pxlong** [comment]
I use command line `python train.py` to train first, then use `ipython` (NOT notebook) to load some data and import predict, then run `new_y = predict.predict_new_velocity(x)` in ipython. 
It works the first time I call `new_y = predict.predict_new_velocity(x)`, but if I run it again, e.g. `new_ty = predict.predict_new_velocity(tx)`, it will fail and output errors like I said.

**Comment by pxlong** [comment]
@aymericdamien I have tested the .ipynb you shared. It also has this problem:
`predict_new_velocity(testX[0])` works well, but if I run it again:
`predict_new_velocity(testX[1])` does not work anymore.

I am writing a program to load the saved model to predict new y once I get a new x, so I want to figure out a way to call the predice_new_velocity function multiple times.

**Comment by aymericdamien** [comment]
oh, i get it, it is because your function predict_new_velocity() define a graph, so calling it again, will again add ops to the default graph.

You need to encapsulate the graph definition into a new graph, so it avoid any conflict with a predefined graph:
```
def predict_new_velocity(x):
    with tf.Graph().as_default():
        # Building deep neural network
        input_layer = tflearn.input_data(shape=[None, 360, 3])
        dense1 = tflearn.fully_connected(input_layer, 64, activation='relu',
                                        regularizer='L2', weight_decay=0.001)
        dropout1 = tflearn.dropout(dense1, 0.5)
        dense2 = tflearn.fully_connected(dropout1, 64, activation='relu',
                                        regularizer='L2', weight_decay=0.001)
        dropout2 = tflearn.dropout(dense2, 0.5)
        softmax = tflearn.fully_connected(dropout2, 8, activation='softmax')

        # Regression using SGD with learning rate decay and Top-3 accuracy
        sgd = tflearn.SGD(learning_rate=0.1, lr_decay=0.96, decay_step=1000)
        top_k = tflearn.metrics.Top_k(3)
        net = tflearn.regression(softmax, optimizer=sgd, metric=top_k,
                                loss='categorical_crossentropy')

        # load the trained model
        model = tflearn.DNN(net, tensorboard_verbose=3)
        model.load("model.tflearn")

        predict_y = model.predict(x)
        new_y = np.argmax(predict_y, axis=1)
        return new_y.astype(np.uint8)
```

For further optimization, you can simply load graph once, store the DNN class in a global variable for example, and just call it, so you do not need to redefined graph and load weights at every prediction.

**Comment by aymericdamien** [comment]
[issue32_1.ipynb.txt](https://github.com/tflearn/tflearn/files/218659/issue32_1.ipynb.txt)

**Comment by pxlong** [comment]
Thanks so much @aymericdamien, it works now !!!

I really love this API, it makes my research projects much easier, thank you for your help and contributions.
