### ISSUE TITLE
variable_scope() got multiple values for argument 'reuse'

### ISSUE THREAD

**Issue by ror6ax** [tflearn/tflearn#389]
I'm getting the following error:

```
Traceback (most recent call last):
  File "book.py", line 15, in <module>
    net = tflearn.fully_connected(net, 64)
  File "/usr/local/lib/python3.5/site-packages/tflearn/layers/core.py", line 146, in fully_connected
    with tf.variable_scope(scope, name, values=[incoming], reuse=reuse) as scope:
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 133, in helper
    return _GeneratorContextManager(func, args, kwds)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 38, in __init__
    self.gen = func(*args, **kwds)
TypeError: variable_scope() got multiple values for argument 'reuse'

```

by executing this code:

```

dataset_file = 'my_dataset.txt'
from tflearn.data_utils import image_preloader
import tflearn
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.data_preprocessing import ImagePreprocessing
from tflearn.data_augmentation import ImageAugmentation
from tflearn.layers.conv import conv_2d, max_pool_2d

X, Y = image_preloader(dataset_file, image_shape=(128, 128),   mode='file', categorical_labels=True,   normalize=True)
# Classification
tflearn.init_graph(num_cores=8, gpu_memory_fraction=0.5)

net = tflearn.input_data(shape=[None, 784])
net = tflearn.fully_connected(net, 64)
net = tflearn.dropout(net, 0.5)
net = tflearn.fully_connected(net, 10, activation='softmax')
net = tflearn.regression(net, optimizer='adam', loss='categorical_crossentropy')

model = tflearn.DNN(net)
model.fit(X, Y)
```
Please advice.

**Comment by ror6ax** [comment]
The titanic example from your tutorial section causes same error.

**Comment by inancarin** [comment]
Hi @ror6ax ,

I installed tflearn on my new machine and I had the same problem with you. I think they are changing tflearn version. Currently version 0_2_1 is available, but we used to use version 0_2_2 before. I think they may have removed this version because of some bugs on conv1_d functions. Luckily I had this 0_2_2 version on my other computer where everything works file. 

You can reach these files on https://github.com/inancarin/tflearn_0_2_2_package
Put these folders under (if you are using anaconda) /anaconda/envs/tensorflow/lib/python2.7/site-packages (ofcourse after you removed previous tflearn version)

**Comment by SomeKittens** [comment]
Also getting this.  Debug info:

OS: Linux Mint
Python version: 3.4.4
TensorFlow version: 0.9.0 (64 bit, GPU enabled)
tflearn version: 0.2.2

code:

```python
import tflearn

# Build neural network
net = tflearn.input_data(shape=[None, 67])
net = tflearn.fully_connected(net, 32)
net = tflearn.fully_connected(net, 32)
net = tflearn.fully_connected(net, 2, activation='softmax')
net = tflearn.regression(net)
```

**Comment by SomeKittens** [comment]
Digging around a bit, here's the offending line:

```python
with tf.variable_scope(scope, name, values=[incoming], reuse=reuse) as scope:
```

For TF 0.9.x, the shape of `variable_scope` is:

```python
tf.variable_scope(name_or_scope, reuse=None, initializer=None, regularizer=None, caching_device=None, partitioner=None)
```

So, our problem is that we're passing the `name` variable in where Python's expecting `reuse` to go, and _also_ providing a named argument for `reuse`.  A bit obvious from the stack trace.  I'll keep digging.

@inancarin I'm running version 0.2.2, so that's not the problem.

**Comment by SomeKittens** [comment]
Ok, final update, I swear: Upgraded to TensorFlow 0.11.0rc0 and it worked

**Comment by ror6ax** [comment]
Same with @SomeKittens. Now tensorboard does not work, but I've raised that to tensorflow repo.
I think this is kinda broken since 0.9.0 is current stable, but at least there is a workaround.

**Comment by inancarin** [comment]
@SomeKittens oh sorry, I forgot to say which version of tensorflow I am using. I tested these with tensorflow 0.10 and 0.11 it's working with tflearn 0.2.2 . 

@ror6ax I tested tensorboard on tensorflow 0.10 and tflearn 0.2.2 and it is working for me.

I hope, they will make it work in a stable way as soon as possible, because tflearn started to has an important role for us.

**Comment by aymericdamien** [comment]
This issue has been fix, it should be working fine for any version of TensorFlow now.
