### ISSUE TITLE
High accuracy but bad prediction with AlexNet

### ISSUE THREAD

**Issue by TrinhTUHH** [tflearn/tflearn#832]
Hi everyone,
I have trained the AlexNet with the dataset of 17 different flowers. The accuracy is quite high is you can see in the picture :
![image](https://user-images.githubusercontent.com/19979949/28059714-636171b4-6625-11e7-89e8-ac332fe9e1ef.png)

However when I created another file to test the result, the predictions were very bad even when I tested with the images in the dataset itself. One note is that because of OOM (out of memory) error, I did decrease the size of last 2 fully connected layers to 2048, but I don't see any problem with this. Does anyone know the reason why?

Here is the code of the test file. I just print out the number corresponding to the folder of the flowers but it does not match most of the time, like 80% fail.
[testAlex.py.zip](https://github.com/tflearn/tflearn/files/1138254/testAlex.py.zip)

**Comment by Legor** [comment]
Hi, if you use the same images that you have used for training you should see good results as indeed your training accuracy is very high. So if you get a wrong classification result for the same images as you say, it almost certainly has to do with your preprocessing of the images and not with the network topology.

My guess would be that you do not normalize your images the same way in the test as you do in the training. But i cant tell for sure since you didnt show the code you used for the network training. 

To be more specific if you load an image with 
`img = scipy.ndimage.imread(args.image, mode="RGB")` 
it will have values from [0, 255]. 

After your transform 
`img = scipy.misc.imresize(img, (227, 227), interp="bicubic").astype(np.float32, casting='unsafe')` 
it will still have values in the range [0.0, 255.0] but in your training your images will probably have been normalized to the range [0.0, 1.0]. So in that case it would be perfectly explainable that you test and training performance is that much different.

**Comment by TrinhTUHH** [comment]
Hi Legor,
Thank you for replying me. Here is my training code which I took from tflearn/example. 
[alexNet.py.zip](https://github.com/tflearn/tflearn/files/1141744/alexNet.py.zip)
You're probably right. Could you tell me how to normalize the image? I'm pretty new with all this.

**Comment by Legor** [comment]
Hi, as you can see from the code the images downloaded and used for your training are indeed normalized to [0.0, 1.0].
```python
import tflearn.datasets.oxflower17 as oxflower17
X, Y = oxflower17.load_data(one_hot=True, resize_pics=(227, 227))
X.min()
[Out] 0.0
X.max()
[Out] 1.0
```
So if you use the exact images for testing you should be good. However if you load another image of your own you have to make sure its pixel values are in the same range as in your training. By the way due to my own experiences it is always best to normalize the values to the range [0.0, 1.0] when training a neural net, regardless of the concrete application.
 
To normalize your images in testing there are several ways, however the most simple way for images is to do
```python
J = J / 255.0
```
Please be aware that this only holds true for uint8 images with a value range of [0, 255].

Another personal oppinion. You shouldn't use scipy.misc.imresize since it is known to change the value range of the image (due to interpolation) which may have a large effect on the overall features that are helpfull to classify an image. It is mentioned here scipy/scipy#4458

So here is a short snippet how it can be done using Pillow and numpy:
```python
from PIL import Image
import numpy as np

J = Image.open('image.png')
J = J.resize([227,227])
J = np.asarray(J).astype(float)
J /= 255.0
```
After this you could try to feed it into your classifier.

**Comment by TrinhTUHH** [comment]
Thank you very much, Legor! I have tried your script and it worked. Sometimes the output of `np.argmax(prediction)` are not the same with the number of folders in the dataset, but testing many photos in a same folder always output a same number so I think the order is a bit different (for example, when I tested all images in folder 2, the output of argmax is always 9). I also did try with other normalization like `J = (J - min(J))/(max(J)-min(J))` and it worked too. Again, Thank you very much for your help!

**Comment by Yimin-Yuan** [comment]
> Thank you very much, Legor! I have tried your script and it worked. Sometimes the output of `np.argmax(prediction)` are not the same with the number of folders in the dataset, but testing many photos in a same folder always output a same number so I think the order is a bit different (for example, when I tested all images in folder 2, the output of argmax is always 9). I also did try with other normalization like `J = (J - min(J))/(max(J)-min(J))` and it worked too. Again, Thank you very much for your help!

Thanks! Since I've met the same problem with you, can I see your code for help?
