### ISSUE TITLE
How can I training using decay learning rates but using variable decay steps?

### ISSUE THREAD

**Issue by lfwin** [tflearn/tflearn#91]
Right,no, is this only be achieved by model.save() function?
Thx.

**Comment by aymericdamien** [comment]
Yes, unfortunately now TFLearn is only accepting fix decay step. So, as a hack, you have to save / load and change regression layer in order to change learning rate.
Seem that it would be beneficial for many user to have such variable decay for learning rate, so we can work on integrating this feature to TFLearn.
